# https://f-droid.org/en/docs/Build_Metadata_Reference/
RepoType: git
Repo: https://github.com/crazydan-studio/kuaizi-ime-android

Builds:
  - versionName: {{version_name}}
    versionCode: {{version_code}}
    commit: master
    subdir: app
    submodules: true
    gradle:
      - yes
    prebuild:
      # NOTE: 当前在 subdir 指向的目录中
      - cd ../libtrime/src/main/jni
      - patch -p1 -d librime-lua-deps < patches/lua.patch
    scandelete:
      - libtrime/src/main/jni
    ndk: {{ndk_version}}
