FROM registry.gitlab.com/fdroid/docker-executable-fdroidserver:master

RUN apt-get update && apt-get install -y \
        automake g++ libtool make python-is-python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
